# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp
#   namespace: default
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: myapp
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: myapp
#         image: hieunguyen609/myapp:latest
#         ports:
#         - containerPort: 8000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hieunguyen609/myapp:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080   # để bạn test qua NodeIP:30080
  type: NodePort
