apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8000        # Cổng service trong cluster
      targetPort: 8000  # Cổng container (gunicorn)
      type: NodePort        # Hoặc LoadBalancer nếu cloud provider hỗ trợ
